

services:
  db-estoque:
    image: postgres:16
    container_name: db-estoque
    environment:
      POSTGRES_DB: estoque
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"

  db-faturamento:
    image: postgres:16
    container_name: db-faturamento
    environment:
      POSTGRES_DB: faturamento
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"